import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavBar from '../app/components/navbar';
import Footer from '../app/components/footer';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Range Shopify Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">


      <body
        className={`h-screen flex flex-col ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />
        {/* NOTE to SELF */}
        {/* <body> had h-screen and <main> had h-4/6. h-screen = 100vh   h-4/6 = ~66% of parent
            The remaining space is less than needed, so footer can appear mid-page when content is short or small screens
            Using fractional heights (Ex. h-4/6) leads to subpixel rounding and clipping which causes page content to overlap with footer
              Fix:
              Removed h-4/6 on <main>.
              Use only flex layout with flex-1 to fill the space */}
        <main className="flex-1 w-full "
        >
          {children}
        </main>

        <Footer />
      </body>


    </html>
  );
}
